version: '3.8'

# Daftar layanan (container/dapur) apa saja yang mau jalankan
services:
  # Nama layanan adalah 'frontend'
  frontend:
    # Instruksi untuk membangun Image dari Dockerfile
    build:
      # Cari file resepnya di folder saat ini (titik .)
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    # Konfigurasi Volumes untuk mengaktifkan fitur Hot Reload
    volumes:
      # Pipa 1: Sambungkan folder project di Windows (./) ke folder /app di container
      - ./:/app
      # Pipa 2 (Trick Docker): Lindungi folder node_modules di dalam container agar tidak tertimpa oleh Windows
      - /app/node_modules
    # Setel variabel lingkungan (environment variables)
    environment:
      # Beri tahu Vite agar menggunakan mekanisme "polling" (mengecek berkala) untuk mendeteksi perubahan file
      - CHOKIDAR_USEPOLLING=true
